### Signup Test for testuser

POST http://localhost:8000/signup/
Content-Type: application/json

{
  "username": "testuser",
  "email": "testuser@example.com",
  "password": "password123",
  "first_name": "Test",
  "last_name": "User"
}

###

### Login Test for testuser

POST http://localhost:8000/login/
Content-Type: application/json

{
  "username": "alex",
  "password": "qwerty"
}

###

### Login Test for invalid user

POST http://localhost:8000/login/
Content-Type: application/json

{
  "username": "invaliduser",
  "password": "invalidpassword"
}

###

### Auth token generation

POST http://localhost:8000/token_auth_generate/
Content-Type: application/json

{
  "username": "testuser",
  "password": "password123"
}

###

### Add camera url

POST http://localhost:8000/addCamera/
Authorization: Token 39f4c9b79185f77e88adfe62e354ac1c720e741d
Content-Type: application/json

{
  "name": "New Camera",
  "latitude": "34.0522",
  "longitude": "-118.2437"
}

